<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HAMZA" name="sirmayaCRM.Addclient_Test" tests="5" failures="0" timestamp="04 Jul 2019 09:42:21 GMT" time="49.270" errors="1">
  <testcase name="opensite" time="11.342" classname="sirmayaCRM.Addclient_Test"/>
  <testcase name="invalidcredentials" time="2.100" classname="sirmayaCRM.Addclient_Test"/>
  <testcase name="validcredentials" time="14.468" classname="sirmayaCRM.Addclient_Test"/>
  <testcase name="single_invalidsearching" time="21.356" classname="sirmayaCRM.Addclient_Test"/>
  <testcase name="addclients" time="0.004" classname="sirmayaCRM.Addclient_Test">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at sirmayaCRM_ObjectsRepo.add_clientpage_Repo.addclient_button(add_clientpage_Repo.java:81)
at sirmayaCRM.Addclient_Test.emptydetails_check(Addclient_Test.java:28)
at sirmayaCRM.Login_pageTest.addclients(Login_pageTest.java:409)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- addclients -->
</testsuite> <!-- sirmayaCRM.Addclient_Test -->
